name: Setup Continuous Integration
description: Setup Continuous Integration
runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20.x

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@8b0419c685ef46cb79ec93fbdc131174afceb730 # v1.6.0

    - name: Install yarn
      run: npm install -g yarn
      shell: bash

    - name: Get yarn cache directory
      id: yarn-cache
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Retrieve yarn cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install packages
      run: yarn install --frozen-lockfile
      shell: bash
