name: Continuous Integration
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint_and_test:
    runs-on: small-dind-spot
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          policy: global-allowed-endpoints-policy

      - name: Check out repository code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run Linter
        run: yarn lint

      - name: Run Forge fmt
        run: yarn format:check

      - name: Run Unit Tests
        run: yarn test

  scan:
    needs: lint_and_test
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint_and_test
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
