name: Continuous Integration
on:
  pull_request:
jobs:
  lint_and_test:
    runs-on: small-dind-spot
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      # TODO: enable this in next PR
      # - name: Run Linter
      #   run: yarn lint

      # - name: Run Forge fmt
      #   run: yarn format:check

      - name: Run Unit Tests
        run: yarn test
